google_project_id       = "dynamic-cove-315502"
google_bucket_name      = "aaronyildiztas-bucket"
deployment_environment  = "qa"
deployment_name         = "hello-world"
credentials             = "fuchicorp-service-account.json"